### ISSUE TITLE
keras 2.0.1

### ISSUE THREAD

**Issue by juliojj** [coxlab/prednet#13]
Hi, 
I adapted your code to my needs and it was working perfectly until I installed the latest keras version (2.0.1). Did some of you tried to run prednet with keras 2.0? The error I am getting is the following (even if I use 'th' or 'tf'). Any suggestion to fix that will be very appreciated. Thanks a lot.

--------
/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(1, (3, 3), padding="same", activation=<function ..., data_format="channels_last")`
  '` call to the Keras 2 API: ' + signature)
/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(1, (3, 3), padding="same", activation="relu", data_format="channels_last")`
  '` call to the Keras 2 API: ' + signature)
/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(48, (3, 3), padding="same", activation=<function ..., data_format="channels_last")`
  '` call to the Keras 2 API: ' + signature)
/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(96, (3, 3), padding="same", activation=<function ..., data_format="channels_last")`
  '` call to the Keras 2 API: ' + signature)
/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(192, (3, 3), padding="same", activation=<function ..., data_format="channels_last")`
  '` call to the Keras 2 API: ' + signature)
Traceback (most recent call last):
  File "predictSpatioTemporal.py", line 267, in <module>
    cache_dir=cache_dir)
  File "predictSpatioTemporal.py", line 173, in predictSpatioTemporal
    train_prednet_model()
  File "code/chalearn_train.py", line 71, in train_prednet_model
    errors = prednet(inputs)  # errors will be (batch_size, nt, nb_layers)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 252, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 528, in __call__
    self.build(input_shapes[0])
  File "code/prednet.py", line 196, in build
    if self.initial_weights is not None:
AttributeError: 'PredNet' object has no attribute 'initial_weights'

**Comment by bill-lotter** [comment]
Hi, I haven't updated for Keras 2.0 yet but hope to do so in the not-too-distant future.

**Comment by yaxiongchi** [comment]
I met the same problem

**Comment by Keson96** [comment]
Met the same problem with Keras 2.0
I downgraded to Keras 1.2.0 and Tensorflow 0.12.1, still got following error

ValueError: Dimension 0 in both shapes must be equal, but are 32 and 16 for 'concat_5' (op: 'Concat') with input shapes: [], [?,3,128,160], [?,48,64,80], [?,96,32,40], [?,192,16,20], [?,3,128,160], [?,48,64,80], [?,96,32,40], [?,192,16,20], [?,6,128,160], [?,96,64,80], [?,192,32,40], [?,384,16,20].

I haven't tried using python 2.7 because Tensorflow only has python 3.5 support on windows. Is this error related with Python version？
Any suggestion will be appreciated. Thanks a lot.

**Comment by youxiangyien** [comment]
I met the same problem,have you found a solution?

**Comment by cpaxton** [comment]
At least for me, I only needed a couple minor changes to get training to work with Keras 2.0: https://github.com/cpaxton/prednet/commit/b25db2a12ebbc13ca635759de9e925600fc79108

**Comment by bill-lotter** [comment]
It's now compatible with Keras 2.0.  Thanks for the patience and let me know if you run into any issues with it!
